spring:
  profiles:
    active: dev
  dataSource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.20:5432/vacancy
    username: ${PG_USER:vasi}
    password: ${PG_PASSWORD:pass}
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    generate_statistics: true
    baseline-on-migrate: true
  cache:
    type: caffeine
    cache-names: companies,company
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
server:
  port: 8443
  ssl.enabled: true
  ssl.key-store: /home/vasi/prog/sert/spring/v_perm_ru.p12
  ssl.key-store-password: Bazilio67
  ssl.keyStoreType: PKCS12

security.require-ssl: true

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/api/actuator"
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 8788

