spring:
  dataSource:
    url: jdbc:postgresql://127.0.0.1:5432/vacancy
    username: ${PG_USER:vasi}
    password: ${PG_PASSWORD:pass}
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    generate_statistics: true

server:
  port: 443
  servlet:
    context-path: /api
  include-message: always
  ssl:
    keyStore: classpath:keystore/
    keyStorePassword: pass
    keyStoreType: PKCS12
    keyAlias: tomcat