server:
  port: 8080
  servlet:
    context-path: /api
  include-message: always

spring:
  dataSource:
    url: jdbc:postgresql://192.168.1.20:5432/vacancy
    username: vasi
    password: pass
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    generate_statistics: true
    baseline-on-migrate: true

